#!/bin/sh

docker build -t 5pi_nginx universe/nginx
docker run -e SERVER_KEY="$(cat secrets/5pi_de.key)" 5pi_nginx -t

docker inspect nginx-data   || docker run --name nginx-data --volume /www busybox true
docker inspect nginx-server || docker run --restart=always --name nginx-server -e SERVER_KEY="$(cat secrets/5pi_de.key)" -d --net=host --volumes-from nginx-data 5pi_nginx
#docker inspect nginx-server || docker run --restart=always --name nginx-server -d -p 80:80 -p 443:443 --volumes-from nginx-data 5pi_nginx
